<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ContextSmith.Application\ContextSmith.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.Search.Documents" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

</Project>
