<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ContextSmith.Documents.Docx\ContextSmith.Documents.Docx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\samples\documents\sample.docx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
